AWSTemplateFormatVersion: "2010-09-09"
Description: "SageMaker Workshop - CloudFormation Template - Backend"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "SageMaker Configuration"
        Parameters:
          - Endpoint
      - Label:
          default: "Lambda Configuration"
        Parameters:
          - PrivateBucket

Parameters:
  Endpoint:
    Type: String
    Description: "SageMaker endpoint for mammography classifier."
  PrivateBucket:
    Type: String
    Description: "Bucket with lambda code."
  SetUpBucket:
    Type: String
    Description: "Bucket with OpenCV layer."
  

Resources:
  LambdaGodRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "lambda-god-${AWS::AccountId}"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  InvokeFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref PrivateBucket
        S3Key: code/lambda_invoke_classifier.zip
      Description: Orquestrator
      Environment:
        Variables:
          endpoint_name: !Ref Endpoint
      FunctionName: InvokeMammographyClassification
      Handler: lambda_invoke_classifier.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaGodRole.Arn
      Runtime: python3.7
      Timeout: 30

  OpenCVLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.7
      Content:
        S3Bucket: !Ref SetUpBucket
        S3Key: opencv-layer/opencv-python37-layer.zip
      Description: opencv-python37
      LayerName: opencv-python37

  ResizeFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref PrivateBucket
        S3Key: code/lambda_resize_image.zip
      Description: Resize Image
      Environment:
        Variables:
          PYTHONPATH: /opt/
      FunctionName: ResizeMammography
      Handler: lambda_resize_image.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaGodRole.Arn
      Runtime: python3.7
      Timeout: 10
      Layers:
        - !Ref OpenCVLayer
